repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-yaml
        files: .*\.(yaml|yml)$

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        files: ^src/|tests/

-   repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v0.910
    hooks:
    -   id: mypy
        files: ^src/|tests/

-   repo: https://github.com/python/black
    rev: 21.7b0
    hooks:
    -   id: black
        files: ^src/|tests/

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        files: ^src/|tests/

-   repo: local
    hooks:
    -   id: tests
        name: Tests
        entry: pytest
        language: system
        stages: [push]
        pass_filenames: false
